Adapp 18520 create flutter sdk v4 to v5 migration and v5 integration guide
adjust/dev-docs pull request #1016
Opened 2024-08-28 10:41 UTC by ivosam3

SDK v5 migration guide for Flutter

2024-08-29 07:53 UTC, shashanksu requested changes

2024-08-29 07:53 UTC, shashanksu commented on src/content/docs/sdk/flutter/features/subscriptions.mdx
> +   receipt);
`receipt` to be removed.

2024-08-29 07:53 UTC, shashanksu commented on src/content/docs/sdk/flutter/features/subscriptions.mdx
> +   receipt);
`receipt` to be removed.

2024-08-29 07:53 UTC, shashanksu commented on src/content/docs/sdk/flutter/features/subscriptions.mdx
> +   receipt);
`receipt` to be removed.

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +1. SDK v5 supports [SDK signature verification](https://help.adjust.com/en/article/sdk-signature) natively. If you currently use the SDK signature library, you need to uninstall this first.
I'd not say `uninstall`, that's more of an app terminology. They should remove the signature library from their app.

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +   ## [Install the SDK](install-the-sdk)
Not sure if this is the reason, but formatting of this title seems to be a bit skewed (too close to "Android" line). Could it be because of the empty spaces in front?

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +1. Remove any older versions of the SDK you currently have in your `pubspec.yaml` file.
They don't really need to remove anything. If they were using v4 of the SDK, they just need to change the version number in the `pubspec.yaml` from 4.X.Y to 5.0.0 and that's it.

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +   adjust_sdk: 5.0.0
In v4, we have used annotation:

```yaml
adjust_sdk: ^4.X.Y
```

This pretty much meant: Always use latest version starting from 4.X.Y, but up to 5.0.0 (not including 5.0.0). I don't see the reason not to continue with that approach, having in mind that we're making all the SDK versions backend compatible within the same major version. So I'd suggest changing this to:

```yaml
adjust_sdk: ^5.0.0
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +In SDK v4, the initialization method is `Adjust.start;`. This has been changed to `Adjust.initSdk` in SDK v5.
```suggestion
In SDK v4, the initialization method is `Adjust.start`. This has been changed to `Adjust.initSdk` in SDK v5.
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +In SDK v4, you can enable and disable the SDK by calling `Adjust.setEnabled` with a `boolean` value.
```suggestion
In SDK v4, you can enable and disable the SDK by calling `Adjust.setEnabled` with a `bool` value.
```

Dart is naming this primitive data type `bool`.

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +-  Call `Adjust.disable;` to disable the SDK.
```suggestion
-  Call `Adjust.disable` to disable the SDK.
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +-  Call `Adjust.enable;` to enable the SDK.
```suggestion
-  Call `Adjust.enable` to enable the SDK.
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +In SDK v4, you can set the `LinkMeEnabled` property on your `adjustConfig` instance to `true` to enable [Adjust LinkMe](https://help.adjust.com/en/article/linkme).
```suggestion
In SDK v4, you can set the `linkMeEnabled` property on your `adjustConfig` instance to `true` to enable [Adjust LinkMe](https://help.adjust.com/en/article/linkme).
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +Adjust.appWillOpenUrl("url");
```suggestion
Adjust.appWillOpenUrl('url');
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +-  `shouldUseSubdomains` (`bool`): Whether the source should prefix a subdomain.
```suggestion
-  `useSubdomains` (`bool`): Whether the source should prefix a subdomain.
```

And I'm not sure if the explanation is good. When users give us domains in the array (1st parameter), this boolean is indicating whether they want us to treat those domains as Adjust domains or not. If we think of them as Adjust domains (`true`), this means that SDK will take what's given in there and prefix those domains with Adjust subdomains prefixes before making requests. For example if someone gives us `adjust.com` as domain, in order to send session request, we will make this out of that domain `app.adjust.com/session` (Android) or `consent.adjust.com/session` / `analytics.adjust.com/session` (iOS) and send request there.

In case this boolean is `false`, that's for the use case where clients might want to forward SDK traffic to their own domain before forwarding it s2s to our backend (https://help.adjust.com/en/article/s2s-sdk-forwarding). In that case they will just give us their domain `['mydomain.com']` and SDK will know that in this case we should not prefix it, since in this setup, we are just appending paths to domain they give us. So session would land on `mydomain.com/session`.

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.DataResidencyEU`   | `"eu.adjust.com"`                 | `true`               | `true`                 |
```suggestion
| `adjustConfig.DataResidencyEU`   | `'eu.adjust.com'`                 | `true`               | `true`                 |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.DataResidencyTR`   | `"tr.adjust.com"`                 | `true`               | `true`                 |
```suggestion
| `adjustConfig.DataResidencyTR`   | `'tr.adjust.com'`                 | `true`               | `true`                 |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.DataResidencyUS`   | `"us.adjust.com"`                 | `true`               | `true`                 |
```suggestion
| `adjustConfig.DataResidencyUS`   | `'us.adjust.com'`                 | `true`               | `true`                 |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.UrlStrategyChina`  | `"adjust.world"`, `"adjust.com"`  | `true`               | `false`                |
```suggestion
| `adjustConfig.UrlStrategyChina`  | `'adjust.world'`, `'adjust.com'`  | `true`               | `false`                |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.UrlStrategyCn`     | `"adjust.cn"`, `"adjust.com"`     | `true`               | `false`                |
```suggestion
| `adjustConfig.UrlStrategyCn`     | `'adjust.cn'`, `'adjust.com'`     | `true`               | `false`                |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.UrlStrategyCnOnly` | `"adjust.cn"`                     | `true`               | `false`                |
```suggestion
| `adjustConfig.UrlStrategyCnOnly` | `'adjust.cn'`                     | `true`               | `false`                |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.UrlStrategyIndia`  | `"adjust.net.in"`, `"adjust.com"` | `true`               | `false`                |
```suggestion
| `adjustConfig.UrlStrategyIndia`  | `'adjust.net.in'`, `'adjust.com'` | `true`               | `false`                |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.AdRevenueAppLovinMAX`            | `"applovin_max_sdk"`      |
```suggestion
| `adjustConfig.AdRevenueAppLovinMAX`            | `'applovin_max_sdk'`      |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.AdRevenueSourceAdMob`            | `"admob_sdk"`             |
```suggestion
| `adjustConfig.AdRevenueSourceAdMob`            | `'admob_sdk'`             |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.AdRevenueSourceIronSource`       | `"ironsource_sdk"`        |
```suggestion
| `adjustConfig.AdRevenueSourceIronSource`       | `'ironsource_sdk'`        |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.AdRevenueSourceAdMost`           | `"admost_sdk"`            |
```suggestion
| `adjustConfig.AdRevenueSourceAdMost`           | `'admost_sdk'`            |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.AdRevenueSourceUnity`            | `"unity_sdk"`             |
```suggestion
| `adjustConfig.AdRevenueSourceUnity`            | `'unity_sdk'`             |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.AdRevenueSourceHeliumChartboost` | `"helium_chartboost_sdk"` |
```suggestion
| `adjustConfig.AdRevenueSourceHeliumChartboost` | `'helium_chartboost_sdk'` |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.AdRevenueSourceADX`              | `"adx_sdk"`               |
```suggestion
| `adjustConfig.AdRevenueSourceADX`              | `'adx_sdk'`               |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.AdRevenueSourcePublisher`        | `"publisher_sdk"`         |
```suggestion
| `adjustConfig.AdRevenueSourcePublisher`        | `'publisher_sdk'`         |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.AdRevenueSourceTradplus`         | `"tradplus_sdk"`          |
```suggestion
| `adjustConfig.AdRevenueSourceTradplus`         | `'tradplus_sdk'`          |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +| `adjustConfig.AdRevenueSourceTopOn`            | `"topon_sdk"`             |
```suggestion
| `adjustConfig.AdRevenueSourceTopOn`            | `'topon_sdk'`             |
```

2024-08-29 08:50 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +#### [Update conversion values](update-cvs)
I guess that meaningfulness of this comment depends on what was meant with title and text in this chapter, but I personally read it as if it's meant that this is about `users` performing updates to the SKAN conversion values. If that's true, then we should reword things in here, since these callbacks are not about clients updating conversion values, but about them registering callbacks which will get pinged once the SDK performs conversion value update because it was instructed by the backend to do so.

SDK also has the ability to let clients to update SKAN conversion values on their own. But it seems to be missing from the migration guide. It is part of [Google document](https://docs.google.com/document/d/10NXWpcrgmzvmnfatdiMeGgJ3Upgm_dktEq1f12ke8s8/edit#heading=h.a463q5pqbnfe) under `Update conversion value` chapter.

2024-08-29 08:53 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +This setting has been removed in SDK v5.
It should also be mentioned that, as part of this removal, [this method](https://github.com/adjust/flutter_sdk/blob/ae24621b7f2930a5e993d85da1997acf6163a243/lib/adjust.dart#L192-L194) has also been removed, since it was a complementary method of this feature which would, if invoked while SDK was in the delay, make SDK to stop the delay and continue with its work.

2024-08-29 08:56 UTC, ivosam3 commented on src/content/docs/sdk/flutter/features/subscriptions.mdx
> +   receipt);
Fixed

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/integrations/tradplus.mdx
> +      AdjustAdRevenue revenue = AdjustAdRevenue("TradPlus");
```suggestion
      AdjustAdRevenue revenue = AdjustAdRevenue('TradPlus');
```
Not just quotations, are you sure it's `TradPlus` and not `tradplus_sdk`? I believe it should be `'tradplus_sdk'` in there.

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +AdjustAdRevenue(this._source) {
```suggestion
AdjustAdRevenue(String source)
```
And you can remove:

```dart
   _callbackParameters = new Map<String, String>();
   _partnerParameters = new Map<String, String>();
}
```

since that's the implementation of the method, it's not part of the signature.

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +| "`applovin_max_sdk`"      | AppLovin MAX      |
```suggestion
| `'applovin_max_sdk'`      | AppLovin MAX      |
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +| "`admob_sdk`"             | AdMob             |
```suggestion
| `'admob_sdk'`             | AdMob             |
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +| "`ironsource_sdk`"        | ironSource        |
```suggestion
| `'ironsource_sdk'`        | ironSource        |
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +| "`admost_sdk`"            | AdMost            |
```suggestion
| `'admost_sdk'`            | AdMost            |
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +| "`unity_sdk`"             | Unity             |
```suggestion
| `'unity_sdk'`             | Unity             |
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +| "`helium_chartboost_sdk`" | Helium Chartboost |
```suggestion
| `'helium_chartboost_sdk'` | Helium Chartboost |
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +| "`adx_sdk`"               | Ad(X)             |
```suggestion
| `'adx_sdk'`               | Ad(X)             |
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +| `"publisher_sdk"`         | Generic source    |
```suggestion
| `'publisher_sdk'`         | Generic source    |
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +| "`tradplus_sdk`"          | TradPlus          |
```suggestion
| `'tradplus_sdk'`          | TradPlus          |
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +| "`topon_sdk`"             | TopOn             |
```suggestion
| `'topon_sdk'`             | TopOn             |
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue("source");
```suggestion
AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue('source');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +void setRevenue(num revenue, String currency) {
```suggestion
void setRevenue(num revenue, String currency)
```
and:
```dart
   _revenue = revenue;
   _currency = currency;
}
```
can be removed since it's not part of the method signature.

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue("source");
```suggestion
AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue('source');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.setRevenue(1.00, "EUR");
```suggestion
adjustAdRevenue.setRevenue(1.00, 'EUR');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue("source");
```suggestion
AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue('source');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue("source");
```suggestion
AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue('source');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.adRevenueNetwork = "network1";
```suggestion
adjustAdRevenue.adRevenueNetwork = 'network1';
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue("source");
```suggestion
AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue('source');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.adRevenueUnit = "unit1";
```suggestion
adjustAdRevenue.adRevenueUnit = 'unit1';
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue("source");
```suggestion
AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue('source');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.adRevenuePlacement = "banner";
```suggestion
adjustAdRevenue.adRevenuePlacement = 'banner';
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +void addCallbackParameter(String key, String value) {
```suggestion
void addCallbackParameter(String key, String value)
```
and:
```dart
   _callbackParameters![key] = value;
}
```
is not needed since it's not part of the method signature.

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue("source");
```suggestion
AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue('source');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.addCallbackParameter("key", "value")
```suggestion
adjustAdRevenue.addCallbackParameter('key', 'value');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +void addPartnerParameter(String key, String value) {
```suggestion
void addPartnerParameter(String key, String value)
```
and:
```dart
   _partnerParameters![key] = value;
}
```
is not needed since it's not part of the method signature.

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue("source");
```suggestion
AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue('source');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.addPartnerParameter("key", "value");
```suggestion
adjustAdRevenue.addPartnerParameter('key', 'value');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue("applovin_max_sdk");
```suggestion
AdjustAdRevenue adjustAdRevenue = new AdjustAdRevenue('applovin_max_sdk');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.setRevenue(1.00, "EUR");
```suggestion
adjustAdRevenue.setRevenue(1.00, 'EUR');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.adRevenueNetwork = "network1";
```suggestion
adjustAdRevenue.adRevenueNetwork = 'network1';
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.adRevenueUnit = "unit1";
```suggestion
adjustAdRevenue.adRevenueUnit = 'unit1';
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.adRevenuePlacement = "banner";
```suggestion
adjustAdRevenue.adRevenuePlacement = 'banner';
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.addCallbackParameter("key1", "value1");
```suggestion
adjustAdRevenue.addCallbackParameter('key1', 'value1');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +adjustAdRevenue.addPartnerParameter("key2", "value2");
```suggestion
adjustAdRevenue.addPartnerParameter('key2', 'value2');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
>  adjustAdRevenue.addPartnerParameter("key2", "value2");
```suggestion
adjustAdRevenue.addPartnerParameter('key2', 'value2');
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/subscriptions.mdx
> +void setTransactionDate(String _transactionDate)
```suggestion
String? transactionDate
```

In v5, it's property, not a method anymore.

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/subscriptions.mdx
> +subscription.setTransactionDate(transactionDate);
```suggestion
subscription.transactionDate = 'transactionDate';
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/subscriptions.mdx
> +subscription.setTransactionDate(transactionDate);
```suggestion
subscription.transactionDate = 'transactionDate';
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/subscriptions.mdx
> +subscription.setSalesRegion(salesRegion);
```suggestion
subscription.salesRegion = 'salesRegion';
```

2024-08-29 09:24 UTC, uerceg commented on src/content/docs/sdk/flutter/features/subscriptions.mdx
> +subscription.setPurchaseTime(purchaseTime);
```suggestion
subscription.purchaseTime = 'purchase-time';
```

2024-08-30 08:46 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +This setting has been removed in SDK v5 including the `checkForNewAttStatus` method. Calling this method would make SDK stop the delay and continue with its work.
```suggestion
This setting has been removed in SDK v5 including the `Adjust.checkForNewAttStatus` method. Calling this method would make SDK stop the delay and continue with its work.
```

2024-08-30 09:15 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +adjustConfig.skanUpdatedCallback = (Map<String, String> skanUpdateData) {
Here's the nicer code snippet:

```dart
config.skanUpdatedCallback = (Map<String, String> skanUpdateData) {
  print('[Adjust]: Received SKAN update information!');
  if (skanUpdateData["conversion_value"] != null) {
    print('[Adjust]: Conversion value: ' + skanUpdateData["conversion_value"]!);
  }
  if (skanUpdateData["coarse_value"] != null) {
    print('[Adjust]: Coarse value: ' + skanUpdateData["coarse_value"]!);
  }
  if (skanUpdateData["lock_window"] != null) {
    print('[Adjust]: Lock window: ' + skanUpdateData["lock_window"]!);
  }
  if (skanUpdateData["error"] != null) {
    print('[Adjust]: Error: ' + skanUpdateData["error"]!);
  }
};
```

2024-08-30 09:15 UTC, uerceg commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +-  `callback` (`Action<string>`): A callback function which can handle any errors that occur
Callback is actually not a parameter of the method. It should probably be removed. One can define callback and chain `.then((error){})` to get information about error if any.

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/integrations/tradplus.mdx
> +        adUnitId = adInfo["adunit_id"].toString();
```suggestion
        adUnitId = adInfo['adunit_id'].toString();
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/integrations/tradplus.mdx
> +        networkName = adInfo["adNetworkName"].toString();
```suggestion
        networkName = adInfo['adNetworkName'].toString();
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/integrations/tradplus.mdx
> +        adType = adInfo["adType"].toString();
```suggestion
        adType = adInfo['adType'].toString();
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/integrations/tradplus.mdx
> +        adUnitId = adInfo["tpAdUnitId"].toString();
```suggestion
        adUnitId = adInfo['tpAdUnitId'].toString();
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/integrations/tradplus.mdx
> +        networkName = adInfo["adSourceName"].toString();
```suggestion
        networkName = adInfo['adSourceName'].toString();
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/integrations/tradplus.mdx
> +        adType = adInfo["format"].toString();
```suggestion
        adType = adInfo['format'].toString();
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/integrations/tradplus.mdx
> +      String ecpmStr = adInfo["ecpm"].toString();
```suggestion
      String ecpmStr = adInfo['ecpm'].toString();
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/integrations/tradplus.mdx
> +      revenue.setRevenue(revenueNum, "USD");
```suggestion
      revenue.setRevenue(revenueNum, 'USD');
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/subscriptions.mdx
> +void setSalesRegion(String _salesRegion)
```suggestion
String? salesRegion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/subscriptions.mdx
> +subscription.setSalesRegion(salesRegion);
```suggestion
subscription.salesRegion = 'sales-region';
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +static void trackAdRevenue(AdjustAdRevenue adRevenue) {
```suggestion
static void trackAdRevenue(AdjustAdRevenue adRevenue)
```
and:
```dart
    _channel.invokeMethod('trackAdRevenue', adRevenue.toMap);
  }
```
can be removed since it's not part of the method signature.

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +//...
```suggestion
```
Not sure why we have these comments, they seem not really useful.

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +//...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +//...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +num? adImpressionsCount;
```suggestion
num? adImpressionsCount
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +//...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +//...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +String? adRevenueNetwork;
```suggestion
String? adRevenueNetwork
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +//...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +//...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +String? adRevenueUnit;
```suggestion
String? adRevenueUnit
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +//...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +//...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +//...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
> +//...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
>  //...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
>  //...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
>  Adjust.trackAdRevenue(adjustAdRevenue);
```suggestion
Adjust.trackAdRevenueNew(adjustAdRevenue);
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
>  //...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
>  //...
```suggestion
```

2024-08-30 09:37 UTC, uerceg commented on src/content/docs/sdk/flutter/features/ad-revenue.mdx
>  Adjust.trackAdRevenue(adjustAdRevenue);
```suggestion
Adjust.trackAdRevenueNew(adjustAdRevenue);
```

2024-08-30 11:34 UTC, ivosam3 commented on src/content/docs/sdk/flutter/migration/v4-to-v5.mdx
> +This section covers changes to ad revenue features in SDK v5.
Added the missing record ad revenue section.

2024-08-30 14:45 UTC, merged