Adapp 18520 flutter sdk v5 integration guide
adjust/dev-docs pull request #1017
Opened 2024-08-28 10:43 UTC by nadinehattom

Updated integration guide (index.mdx) as well as configuration and privacy.

2024-08-28 15:10 UTC, shashanksu commented on src/content/docs/sdk/flutter/index.mdx
> +#### [Meta referrer integration](meta-referrer-integration)
This section needs to update as done for [Android native SDK](https://dev.adjust.com/en/sdk/android/plugins/meta-referrer-plugin?version=v5).  In v5, we introduced Meta Install Referrer as a plugin.

2024-08-28 15:21 UTC, shashanksu requested changes

2024-08-28 15:21 UTC, shashanksu commented on src/content/docs/sdk/flutter/index.mdx
> +Adjust.start(config);
rename `Adjust.start(config)` to `Adjust.initSdk(config);`

2024-08-28 15:34 UTC, shashanksu commented
[AdRevenue constants](https://dev-docs-git-adapp-18520-flutter-sdk-v5-347607-product-content.vercel.app/en/sdk/flutter/features/ad-revenue#instantiate-an-adjustadrevenue-object) are now removed.  In place of that direct values to be used as mentioned [here](https://docs.google.com/document/d/10NXWpcrgmzvmnfatdiMeGgJ3Upgm_dktEq1f12ke8s8/edit#heading=h.wxroijwa4kkj).

2024-08-28 20:19 UTC, nadinehattom commented on src/content/docs/sdk/flutter/index.mdx
> +Adjust.start(config);
Good catch. Fixed.

2024-08-29 06:32 UTC, nadinehattom commented
@ivosam3 can you check the 3 points from @shashanksu for adrevenue, subscriptions and short links. They're in your branch and not in this one. I'm not sure which Shashank checked.

2024-08-29 06:36 UTC, nadinehattom commented on src/content/docs/sdk/flutter/index.mdx
> +#### [Meta referrer integration](meta-referrer-integration)
Updated and added the plugin. @shashanksu can you review the doc again thank you.

2024-08-29 07:11 UTC, ivosam3 commented
> @ivosam3 can you check the 3 points from @shashanksu for adrevenue, subscriptions and short links. They're in your branch and not in this one. I'm not sure which Shashank checked.

Yes, @nadinehattom all those changes are present in my branch. Thank you

2024-08-29 07:13 UTC, ivosam3 commented
> * [AdRevenue constants](https://dev-docs-git-adapp-18520-flutter-sdk-v5-347607-product-content.vercel.app/en/sdk/flutter/features/ad-revenue#instantiate-an-adjustadrevenue-object) are now removed.  In place of that direct values to be used as mentioned [here](https://docs.google.com/document/d/10NXWpcrgmzvmnfatdiMeGgJ3Upgm_dktEq1f12ke8s8/edit#heading=h.wxroijwa4kkj).
> * [Deeplinking](https://dev-docs-git-adapp-18520-flutter-sdk-v5-347607-product-content.vercel.app/en/sdk/flutter/features/deep-links?version=v5) all occurances of `appWillOpenUrl` to replace with updated method name and signature as described [here](https://dev-docs-git-adapp-18520-create-flutter-d7631a-product-content.vercel.app/en/sdk/flutter/migration/v4-to-v5#deep-links).
> * [Subscription](https://dev-docs-git-adapp-18520-flutter-sdk-v5-347607-product-content.vercel.app/en/sdk/flutter/features/subscriptions) - Remove `receipt` as described [here](https://dev-docs-git-adapp-18520-create-flutter-d7631a-product-content.vercel.app/en/sdk/flutter/migration/v4-to-v5#send-subscriptions).
> * [Resolve deep link](https://dev-docs-git-adapp-18520-flutter-sdk-v5-347607-product-content.vercel.app/en/sdk/flutter/features/short-links) - Update method signature as mentioned [here](https://dev-docs-git-adapp-18520-create-flutter-d7631a-product-content.vercel.app/en/sdk/flutter/migration/v4-to-v5#deeplink-resolution).

Sorry for the confusion @shashanksu. I took care of those files and the changes are reflected in my PR.

2024-08-29 07:23 UTC, shashanksu commented on src/content/docs/sdk/flutter/index.mdx
> +#### [Meta referrer integration](meta-referrer-integration)
@nadinehattom Step `1` (adding plugin dependency in build.gradle) as mentioned [here](https://dev.adjust.com/en/sdk/android/plugins/meta-referrer-plugin?version=v5) is missing in [flutter](https://dev-docs-git-adapp-18520-flutter-sdk-v5-347607-product-content.vercel.app/en/sdk/flutter/plugins/meta-referrer-plugin?version=v5).   Can we add that as well?

2024-08-29 07:40 UTC, shashanksu commented
> > * [AdRevenue constants](https://dev-docs-git-adapp-18520-flutter-sdk-v5-347607-product-content.vercel.app/en/sdk/flutter/features/ad-revenue#instantiate-an-adjustadrevenue-object) are now removed.  In place of that direct values to be used as mentioned [here](https://docs.google.com/document/d/10NXWpcrgmzvmnfatdiMeGgJ3Upgm_dktEq1f12ke8s8/edit#heading=h.wxroijwa4kkj).
> > * [Subscription](https://dev-docs-git-adapp-18520-flutter-sdk-v5-347607-product-content.vercel.app/en/sdk/flutter/features/subscriptions) - Remove `receipt` as described [here](https://dev-docs-git-adapp-18520-create-flutter-d7631a-product-content.vercel.app/en/sdk/flutter/migration/v4-to-v5#send-subscriptions).
> > * [Resolve deep link](https://dev-docs-git-adapp-18520-flutter-sdk-v5-347607-product-content.vercel.app/en/sdk/flutter/features/short-links) - Update method signature as mentioned [here](https://dev-docs-git-adapp-18520-create-flutter-d7631a-product-content.vercel.app/en/sdk/flutter/migration/v4-to-v5#deeplink-resolution).
> 
> Sorry for the confusion @shashanksu. I took care of those three files and the changes are reflected in my PR.

No worries @ivosam3 .  Sure I will review these in your PR.

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/index.mdx
> +The install referrer is a unique identifier which you can use to attribute an app install to a source. The Adjust SDK requires this information to perform attribution. There are three methods you can
Chapter is saying `three`, but below there's just a single bullet point. And then later down the text there's mention of META install referrer (so I guess two?). But then also, our SDK is made to handle many install referrers, in case clients opt-in to that.

As far as I know (summoning @shashanksu for sanity check), state of things should be like this:

- Native Android SDK (Flutter SDK included) is supporting Google Play Store install referrer (adding install referrer library is needed for our fallback mechanism to read it).
- All the other install referrers are opt-in and they require a plugin to be added next to the SDK in order for that to work. And they are all supported natively in Android, but we don't have Flutter plugins for any of them. [Those plugins](https://github.com/adjust/android_sdk/tree/master/Adjust/plugins) are:
    - META install referrer
    - Huawei install referrer
    - Samsung install referrer
    - Vivo install referrer
    - Xiaomi install referrer

Like said, none of these comes as a Flutter plugin which can easily be added and used in the Flutter app. There is a possibility for those plugins to be added natively in Flutter app Android Studio project and for them to be activated so that this feature is also supported in Flutter Android app.

So if we want to say what's in the Flutter SDK out of the box, then I'd say that it's only one option and that's Google Play Store install referrer. We can also mention the other ones if there's any use cases for that among Flutter users.

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/index.mdx
> +The Adjust SDK is able to get extra information when you include certain iOS frameworks in your app. These frameworks enable certain SDK features, but they're not mandatory for the SDK to work normal
```suggestion
The Adjust SDK is able to get extra information when you include certain iOS frameworks in your app. These frameworks enable certain SDK features, but they're not mandatory for the SDK to work normally. You can add the frameworks and then mark them as **Optional** in **Project Settings --> Build Phases --> Link Binary With Libraries**.
```
Depending on target audience, leaving these frameworks as `Required` might cause crashes on some devices, so I would stress `Optional`. Also capital O since that's how it's named in the Xcode.

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/index.mdx
> +### [Test Google Play Services integration](test-google-play-services-integration)
Is there some specific reason that this testing chapter is advising only how to check for `gps_adid`? Pretty much the same instructions apply for checking whether IDFA is read properly (parameter name just being `idfa`).

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +AdjustConfig(this._appToken, this._environment) {
```suggestion
AdjustConfig(String appToken, AdjustEnvironment environment)
```
and:
```dart
   _initCallbackHandlers();
   _skAdNetworkHandling = true;
}
```
is not needed, since it's not the part of the method signature.

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +-  `environment` (`String`): The environment you want to run the SDK in. Pass `AdjustEnvironment.sandbox` to run the SDK in sandbox mode for testing. Pass `AdjustEnvironment.production` to run the SD
```suggestion
-  `environment` (`AdjustEnvironment`): The environment you want to run the SDK in. Pass `AdjustEnvironment.sandbox` to run the SDK in sandbox mode for testing. Pass `AdjustEnvironment.production` to run the SDK in production mode for release.
```

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +**Read-only** configuration options are set in your `AdjustConfig` instance **before** the initialization of the SDK. They can't be changed while the SDK is running. You MUST configure any options yo
```suggestion
**Read-only** configuration options are set in your `AdjustConfig` instance **before** the initialization of the SDK. They can't be changed while the SDK is running. You MUST configure any options you want to use before running `Adjust.initSdk`.
```

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +-  `isCostDataInAttributionEnabled` (`bool`): set to `true` to enable cost data sending or `false` to disable cost data sending.
```suggestion
-  `isCostDataInAttributionEnabled` (`bool`): set to `true` to enable cost data sending.
```
No need to set it to `false` since that's the default behavior (explained in the chapter above as well) - that the SDK doesn't send cost data by default.

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +-  `isSendingInBackgroundEnabled` (`bool`): Set to `true` to enable background sending or `false` to disable background sending.
```suggestion
-  `isSendingInBackgroundEnabled` (`bool`): Set to `true` to enable background sending.
```
No need to mention setting to `false` since that's the default SDK behavior.

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +To enable offline mode, call the `Adjust.SwitchToOfflineMode` method.
```suggestion
To enable offline mode, call the `Adjust.switchToOfflineMode` method.
```

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +You can re-enable the SDK by calling the `Adjust.SwitchBackToOnlineMode` method. This prompts the SDK to resume sending information.
```suggestion
You can re-enable the SDK by calling the `Adjust.switchBackToOnlineMode` method. This prompts the SDK to resume sending information.
```

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +<Callout type="note">
Nothing we advise people in terms of web views in Flutter apps, so I'd remove this note.

2024-08-29 11:30 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +Adjust.isEnabled();
```suggestion
Adjust.isEnabled().then((isEnabled) {
    // if isEnabled == true, SDK is enabled
    // if isEnabled == false, SDK is disabled
});
```

2024-08-29 11:53 UTC, nadinehattom commented on src/content/docs/sdk/flutter/configuration.mdx
> +<Callout type="note">
Done

2024-08-29 11:59 UTC, nadinehattom commented on src/content/docs/sdk/flutter/index.mdx
> +The Adjust SDK requires the following permissions. Add them to your `AndroidManifest.xml` file if they're not already present:
@uerceg that's my mistake, I removed INTERNET instead of removing ACCESS_NETWORK_STATE. I've fixed this now.

2024-08-29 12:11 UTC, uerceg commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +#### [Example](example-1)
Same as with session success callback chapter, there doesn't seem to be the need for this chapter, since code snippet above and the one in this chapter do the same thing, but the upper one is nicer.

2024-08-29 12:11 UTC, nadinehattom commented on src/content/docs/sdk/flutter/index.mdx
> +The install referrer is a unique identifier which you can use to attribute an app install to a source. The Adjust SDK requires this information to perform attribution. There are three methods you can
Thanks. I missed that "three".
I removed that. The meta install referrer plugin info is still there in case anyone needs it.
Is that OK?

2024-08-29 12:11 UTC, uerceg commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +| `Adid`         | `String`              | A unique device identifier provided by Adjust.                         |
```suggestion
| `adid`         | `String`              | A unique device identifier provided by Adjust.                         |
```

2024-08-29 12:11 UTC, uerceg commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +| `JsonResponse` | `Map<String, Object>` | The JSON object with the response from the server.                     |
```suggestion
| `jsonResponse` | `String` | The JSON string with the response from the server.                     |
```

2024-08-29 12:12 UTC, uerceg commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +| `EventToken`   | `String`              | The event token                                                        |
```suggestion
| `eventToken`   | `String`              | The event token                                                        |
```

2024-08-29 12:12 UTC, uerceg commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +| `CallbackId`   | `String`              | The custom callback ID set on the event object                         |
```suggestion
| `callbackId`   | `String`              | The custom callback ID set on the event object                         |
```

2024-08-29 12:12 UTC, uerceg commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +| `WillRetry`    | `bool`                | Indicates whether there will be an attempt to resend a failed package. |
```suggestion
| `willRetry`    | `bool`                | Indicates whether there will be an attempt to resend a failed package. |
```

2024-08-29 12:12 UTC, uerceg commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +#### [Example](example-2)
Same as with session success callback chapter, there doesn't seem to be the need for this chapter, since code snippet above and the one in this chapter do the same thing, but the upper one is nicer.

2024-08-29 12:12 UTC, uerceg commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +#### [Example](example-3)
Same as with session success callback chapter, there doesn't seem to be the need for this chapter, since code snippet above and the one in this chapter do the same thing, but the upper one is nicer.

2024-08-29 12:32 UTC, nadinehattom commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +#### [Example](example-2)
Do you mean that we should remove the example?

2024-08-29 12:33 UTC, nadinehattom commented on src/content/docs/sdk/flutter/features/att.mdx
> +### [Example](example-1)
Before I remove it I think I would like to ask @Sporiff.

2024-08-29 12:46 UTC, uerceg commented
Not part of any of the opened PRs, but in same way how you have `getIdfa` in [here](https://dev-docs-git-adapp-18520-flutter-sdk-v5-347607-product-content.vercel.app/en/sdk/flutter/features/device-info), SDK v5 has introduced method called `getIdfv`. Except `a` -> `v` change and ID being identifier for vendors instead for advertisement, paragraph is identical as IDFA one. So you can add that one as well.

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +## [Set up deep linking](set-up-deep-linking)
This entire chapter should probably be revised and replaced so that we give Flutter users `tl;dr` from and point them for more info to https://docs.flutter.dev/ui/navigation/deep-linking. That will probably render bunch of stuff from the current chapter as not needed anymore. Let's open a ticket for it to be done later down the road (and ping SDK team to investigate things from there and write the updated chapter). For the time being, I'll comment on the current state of things.

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +To reattribute your user, you need to instantiate an `AdjustDeeplink` object with your deep link URL and pass it to the `Adjust.processDeeplink` method. The Adjust SDK then looks for new attribution
```suggestion
To reattribute your user, you need to instantiate an `ADJDeeplink`/`AdjustDeeplink` object with your deep link URL and pass it to the `Adjust.processDeeplink` method. The Adjust SDK then looks for new attribution data within the deep link. If the SDK finds new information, it forwards the information to Adjust's servers for reattribution.
```
Class name depends on the platform / programming language.

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +To enable deep linking for iOS, call the `appWillOpenUrl` method with a `true` value inside your app delegate.
```suggestion
To enable Adjust reattribution via deep linking, make sure to call `Adjust.processDeeplink` method once you obtain the deep link in one of your app delegate callbacks.
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +      Adjust.appWillOpenUrl(url)
```suggestion
     let deeplink = ADJDeeplink(deeplink: url)!
     Adjust.processDeeplink(deeplink)
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +            Adjust.appWillOpenUrl(userActivity.webpageURL())
```suggestion
            let deeplink = ADJDeeplink(deeplink: userActivity.webpageURL())!
            Adjust.processDeeplink(deeplink)
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +   [Adjust appWillOpenUrl:url];
```suggestion
   [Adjust processDeeplink:[ADJDeeplink alloc] initWithDeeplink:url]];
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +      [Adjust appWillOpenUrl:[userActivity webpageURL]];
```suggestion
      [Adjust processDeeplink:[ADJDeeplink alloc] initWithDeeplink:[userActivity webpageURL]]];
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +To enable deep linking for Android, call the `appWillOpenUrl` method with a `true` value inside your main activity.
```suggestion
To enable Adjust reattribution via deep linking, make sure to call `Adjust.processDeeplink` method once you obtain the deep link in your activity.
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +      AdjustSdk.appWillOpenUrl(data, this)
```suggestion
      Adjust.processDeeplink(new AdjustDeeplink(data), this)
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +      AdjustSdk.appWillOpenUrl(data, this)
```suggestion
      Adjust.processDeeplink(new AdjustDeeplink(data), this)
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +      AdjustSdk.appWillOpenUrl(data, this);
```suggestion
      Adjust.processDeeplink(new AdjustDeeplink(data), this);
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +      AdjustSdk.appWillOpenUrl(data, this);
```suggestion
      Adjust.processDeeplink(new AdjustDeeplink(data), this);
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +AdjustConfig adjustConfig = new AdjustConfig('{YourAppToken}', AdjustEnvironment.Sandbox);
```suggestion
AdjustConfig adjustConfig = new AdjustConfig('{YourAppToken}', AdjustEnvironment.sandbox);
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +typedef void DeferredDeeplinkCallback(String? uri);
```suggestion
typedef void DeferredDeeplinkCallback(String? deeplink);
```
It was correctly documented, yet, we should probably have more meaningful and platform independent name. /cc @MahdiZTD to add the change. ☝️

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +adjustConfig.deferredDeeplinkCallback = (String uri) {
```suggestion
adjustConfig.deferredDeeplinkCallback = (String? deeplink) {
```
/cc @MahdiZTD ☝️

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +   print('[Adjust]: Received deferred deeplink: ' + uri);
```suggestion
   print('[Adjust]: Received deferred deeplink: ' + deeplink);
```
/cc @MahdiZTD ☝️

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +AdjustConfig adjustConfig = new AdjustConfig(yourAppToken, environment);
```suggestion
AdjustConfig adjustConfig = new AdjustConfig('{YourAppToken}', AdjustEnvironment.sandbox);
```

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +### [Example](example)
Code snippet from above is explaining the same thing as this chapter. We can probably remove the chapter.

2024-08-29 12:50 UTC, uerceg commented on src/content/docs/sdk/flutter/features/deep-links.mdx
> +AdjustConfig adjustConfig = new AdjustConfig('{YourAppToken}', AdjustEnvironment.Sandbox);
```suggestion
AdjustConfig adjustConfig = new AdjustConfig('{YourAppToken}', AdjustEnvironment.sandbox);
```

2024-08-29 21:14 UTC, uerceg commented on src/content/docs/sdk/flutter/features/device-info.mdx
> +The ID for Vendor (IDFV) is a device-specific identifier for Apple devices. You can return the device's IDFV by calling the `Adjust.GetIdfv` method with a callback function. The SDK fetches the infor
```suggestion
The ID for Vendor (IDFV) is a device-specific identifier for Apple devices. You can return the device's IDFV by calling the `Adjust.getIdfv` method with a callback function. The SDK fetches the information asynchronously and passes it to your callback function.
```

2024-08-30 12:32 UTC, ivosam3 commented on src/content/docs/sdk/flutter/features/attribution.mdx
> +The following values can only be accessed if the [`needsCost` property on your `AdjustConfig` instance](/en/sdk/flutter/configuration#enable-cost-data-sending) is `true`:
I checked the configuration file and it's pointing to the right place.

2024-08-30 12:35 UTC, ivosam3 commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +| `Adid`         | `String`              | A unique device identifier provided by Adjust.                         |
Do we need to keep adid? Not sure if the reasoning behind not being part of adjust attribution anymore applies for this file @uerceg

2024-08-30 12:44 UTC, ivosam3 commented on src/content/docs/sdk/flutter/features/privacy.mdx
> +-  `shouldUseSubdomains` (`bool`): Whether the source should prefix a subdomain.
```suggestion
-  `useSubdomains` (`bool`): Whether the domain should be treated as an Adjust domain. If `true`, the SDK will prefix the domains with Adjust-specific subdomains. If `false`, the SDK will use the provided domain as-is, without adding any prefixes.
```

2024-08-30 12:45 UTC, ivosam3 commented on src/content/docs/sdk/flutter/features/privacy.mdx
> +-  `shouldUseSubdomains` (`bool`): Whether the source should prefix a subdomain.
Added parameter explanation

2024-08-30 13:29 UTC, ivosam3 commented on src/content/docs/sdk/flutter/features/attribution.mdx
> +<Callout type="important">
I'd like keep this idea in the loop as we use this callout across all SDKs. Not removing it for now to keep consistency but will discuss with the team.

2024-08-30 13:33 UTC, ivosam3 commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +<Callout type="important">
Also discussing this with the team. Maybe we can specify it in the getting started file once, and remove them from the rest the files. Keeping it for now until we make a decision for the rest of the SDKs

2024-08-30 13:41 UTC, ivosam3 commented on src/content/docs/sdk/flutter/features/callbacks.mdx
> +#### [Example](example)
Yes that's a fair point. It is also something we use across most SDKs. Bringing it up once @Sporiff is back but let's keep it for now.

2024-08-30 14:06 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +AdjustConfig(String appToken, AdjustEnvironment environment){
```suggestion
AdjustConfig(String appToken, AdjustEnvironment environment)
```

2024-08-30 14:06 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +   _initCallbackHandlers();
```suggestion
```

2024-08-30 14:06 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +   _skAdNetworkHandling = true;
```suggestion
```

2024-08-30 14:06 UTC, uerceg commented on src/content/docs/sdk/flutter/configuration.mdx
> +}
```suggestion
```

2024-08-30 14:45 UTC, merged