SDK v5 beta 2
adjust/dev-docs pull request #914
Opened 2024-07-19 13:00 UTC by Sporiff

Closes https://adjustcom.atlassian.net/browse/ADAPP-18310

2024-07-19 13:24 UTC, shashanksu requested changes

2024-07-19 13:24 UTC, shashanksu commented on src/content/docs/sdk/android/migration/v4-to-v5.mdx
> +- Adjust.appWillOpenUrl(Uri url, applicationContext) //v4
`Adjust.apWillOpenUrl(url, applicationContext)`

2024-07-19 13:24 UTC, shashanksu commented on src/content/docs/sdk/android/migration/v4-to-v5.mdx
> ++ Adjust.processDeeplink(AdjustDeeplink data, applicationContext) //v5
`Adjust.processDeeplink(adjustDeeplink, applicationContext)`

2024-07-19 13:24 UTC, shashanksu commented on src/content/docs/sdk/android/migration/v4-to-v5.mdx
> +- Adjust.appWillOpenUrl(Uri url, getApplicationContext()); //v4
`Adjust.appWillOpenUrl(url, getApplicationContext());`

2024-07-19 13:24 UTC, shashanksu commented on src/content/docs/sdk/android/migration/v4-to-v5.mdx
> ++ Adjust.processDeeplink(AdjustDeeplink data, getApplicationContext()); //v5
`Adjust.processDeeplink(adjustDeeplink, getApplicationContext());`

2024-07-19 13:54 UTC, shashanksu requested changes

2024-07-19 13:54 UTC, shashanksu commented on src/content/docs/sdk/android/migration/v4-to-v5.mdx
> ++ Adjust.processDeeplink(data, applicationContext) //v5
`Adjust.processDeeplink(adjustDeeplink, applicationContext)` //v5

2024-07-19 13:54 UTC, shashanksu commented on src/content/docs/sdk/android/migration/v4-to-v5.mdx
> ++ Adjust.processDeeplink(data, getApplicationContext()); //v5
`Adjust.processDeeplink(adjustDeeplinbk, getApplicationContext());`  //v5

2024-07-19 14:43 UTC, shashanksu commented
@Sporiff Android part looks good 👍

2024-07-30 13:34 UTC, Sporiff commented
The Android parts have been cherry-picked out and are live. We can merge the iOS part when the review is complete.

2024-08-02 07:33 UTC, uerceg commented on src/content/docs/sdk/ios/features/privacy.mdx
> +You can prevent the Adjust SDK from reading a device's IDFA by calling the `[ADJConfig disableIdfvReading]` method. When you call this method, the Adjust SDK is prevented from reading the device's ID
Similar to comments from yesterday, `disableIdfv` is not a static, but instance method, so something like:
```objc
[adjustConfig disableIdfvReading];
```
sounds better.

2024-08-02 07:35 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +You can record App Store subscriptions and verify their validity with the Adjust SDK. After the user purchases a subscription, create an `ADJSubscription` instance containing the details.
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:35 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +To get started, you need to create a subscription object containing details of the subscription purchase. To do this, initialize an `ADJSubscription` object using the `initWithPrice` method. Pass the
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:35 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +let subscription = ADJSubscription(
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:35 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +ADJSubscription *subscription = [[ADJSubscription alloc] initWithPrice:price
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:36 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +let subscription = ADJSubscription(
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:36 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +ADJSubscription *subscription = [[ADJSubscription alloc] initWithPrice:price
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:36 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +let subscription = ADJSubscription(
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:36 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +ADJSubscription *subscription = [[ADJSubscription alloc] initWithPrice:price
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:36 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +let subscription = ADJSubscription(
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:36 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +ADJSubscription *subscription = [[ADJSubscription alloc] initWithPrice:price
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:36 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +let subscription = ADJSubscription(
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:36 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +ADJSubscription *subscription = [[ADJSubscription alloc] initWithPrice:price
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:37 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> ++ (void)trackSubscription:(nonnull ADJSubscription *)subscription;
`trackAppStoreSubscription` instead of `trackSubscription`. Also `ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:37 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +Once you have set up your subscription object, you can send it to Adjust using the Adjust SDK. Pass your completed object to the `trackSubscription` method to record the user's subscription purchase.
`trackAppStoreSubscription` instead of `trackSubscription`.

2024-08-02 07:37 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +let subscription = ADJSubscription(
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:37 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +Adjust.trackSubscription(subscription)
`trackAppStoreSubscription` instead of `trackSubscription`.

2024-08-02 07:37 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +ADJSubscription *subscription = [[ADJSubscription alloc] initWithPrice:price
`ADJAppStoreSubscription` instead of `ADJSubscription`.

2024-08-02 07:38 UTC, uerceg commented on src/content/docs/sdk/ios/features/subscriptions.mdx
> +[Adjust trackSubscription:subscription];
`trackAppStoreSubscription` instead of `trackSubscription`.

2024-08-02 07:39 UTC, uerceg commented on src/content/docs/sdk/ios/index.mdx
> +```js
This entire code snippet is now with the official v5 changes brought down to just this:

```js
var yourAppToken = yourAppToken;
var environment = AdjustConfig.EnvironmentSandbox;
var adjustConfig = new AdjustConfig(yourAppToken, environment);
Adjust.appDidLaunch(adjustConfig);
```

2024-08-02 08:55 UTC, merged