Add web bridge migration guides for iOS and Android v5
adjust/dev-docs pull request #947
Opened 2024-08-01 13:07 UTC by Sporiff

2024-08-01 14:31 UTC, shashanksu requested changes

2024-08-01 14:31 UTC, shashanksu commented on src/content/docs/sdk/android/migration/web-v4-to-v5.mdx
> +1. Add the beta repository to your `build.gradle` file.
This is only applicable for beta.  With v5 stable release, this step would not be needed.

2024-08-01 14:31 UTC, shashanksu commented on src/content/docs/sdk/android/migration/web-v4-to-v5.mdx
> +      implementation 'com.adjust.sdk:adjust-android:5.0.0-SNAPSHOT'
This is only applicable for beta. With v5 stable release the version would be 5.0.0 (without `-SNAPSHOT`)

2024-08-01 14:31 UTC, shashanksu commented on src/content/docs/sdk/android/migration/web-v4-to-v5.mdx
> +Adjust.enableCoppaCompliance();
This is now again changed to:
```
adjustConfig.enableCoppaCompliance();
```

2024-08-01 14:31 UTC, shashanksu commented on src/content/docs/sdk/android/migration/web-v4-to-v5.mdx
> +Adjust.enablePlayStoreKidsCompliance();
This is now again changed to:
```
adjustConfig.enablePlayStoreKidsCompliance();
```

2024-08-01 14:55 UTC, Aditi3 commented
Hi @Sporiff 

For iOS Web Bridge migration guide the [following section](https://dev.adjust.com/en/sdk/ios?version=v4#integrate-adjustbridge-into-your-web-view) has been removed and updated with below code snippet - 

```
 var yourAppToken = yourAppToken;
 var environment = AdjustConfig.EnvironmentSandbox;
 var adjustConfig = new AdjustConfig(yourAppToken, environment);
 Adjust.initSdk(adjustConfig);
```

2024-08-02 07:52 UTC, Aditi3 commented
For FB Pixel, 

The code snippet over here - https://dev.adjust.com/en/sdk/ios/plugins/facebook-pixel/#adjust-sdk-integration, changes to -

```
- (void)viewWillAppear:(BOOL)animated {
   
   WKWebView *wkWebView = [[WKWebView alloc] initWithFrame:self.view.frame];
    /// add @property (nonatomic, strong) AdjustBridge *adjustBridge; on your interface
   self.adjustBridge = [[AdjustBridge alloc] init];
   [self.adjustBridge augmentHybridWebView];
   [self.adjustBridge loadWKWebViewBridge:wkWebView];
    
  }
```

2024-08-02 10:26 UTC, Sporiff commented
@uerceg @Aditi3 The iOS web bridge migration guide is available [here](https://dev-docs-git-adapp-18258-add-web-bridge-1864b7-product-content.vercel.app/en/sdk/ios/migration/web-v4-to-v5)

I will be adding the JS code snippets to the relevant places in the documentation for the next little while. I'll ping again when it's done. After that, I'll merge everything and update #948 so that you can take a look at how everything is going to look prior to merge.

2024-08-02 11:01 UTC, uerceg commented
@Aditi3 Can double check the code syntax, but yeah, the initialization snippets still to be added and I believe that the part for adding web bridge via CocoaPods also need to be changed (@Aditi3 can confirm that part as well).

2024-08-02 11:11 UTC, Aditi3 commented on src/content/docs/sdk/ios/migration/web-v4-to-v5.mdx
> +   pod 'Adjust', :git => 'https://github.com/adjust/ios_sdk.git', :branch => 'v5'
```suggestion
   pod 'Adjust/AdjustWebBridge', :git => 'https://github.com/adjust/ios_sdk.git', :branch => 'v5'
```

2024-08-02 11:17 UTC, uerceg commented on src/content/docs/sdk/ios/migration/web-v4-to-v5.mdx
> +   pod 'Adjust', :git => 'https://github.com/adjust/ios_sdk.git', :branch => 'v5'
Is this aiming beta or official release? If it's for the official release, then:

```
pod 'Adjust/AdjustWebBridge', :git => 'https://github.com/adjust/ios_sdk.git', :tag => 'v5.0.0'
```

2024-08-02 11:55 UTC, Aditi3 commented
> @Aditi3 Can double check the code syntax, but yeah, the initialization snippets still to be added and I believe that the part for adding web bridge via CocoaPods also need to be changed (@Aditi3 can confirm that part as well).

Yes, this could be part of migration guide - https://github.com/adjust/dev-docs/pull/947#issuecomment-2263284222

2024-08-02 12:53 UTC, Sporiff commented
@uerceg @Aditi3 @shashanksu I'm merging this branch into #948 so you can go through and review everything in one place. I'll ping you the Android/iOS link once the build is finished.

2024-08-02 12:53 UTC, merged